stagingEnabled: true
prodEnabled: false

stagingClusterIssuerName: letsencrypt-staging
stagingCertificateName: stable1-apimgcp-com-staging
stagingCertificateSecretName: stable1-apimgcp-com-tls-staging

prodClusterIssuerName: letsencrypt-prod
prodCertificateName: stable1-apimgcp-com-prod
prodCertificateSecretName: stable1-apimgcp-com-tls-prod

dnsProviderName: clouddns
certDomainName: '*.stable1.apimgcp.com'

acmeEmail: # set email address here

# Google Cloud DNS details for ClusterIssuer ACME DNS01 validation
clouddnsServiceAccountSecretRefName: clouddns
<<<<<<< HEAD
clouddnsServiceAccountSecretRefKey: clouddns1.key.json
clouddnsProject: demos-esd-security-masingale
clouddnsServiceAccountKeyFile: # set this key with --set-file
=======
clouddnsServiceAccountSecretRefKey: clouddns.key.json
clouddnsProject: demos-esd-security-masingale
clouddnsServiceAccountKeyFile: # set this key with --set-file
>>>>>>> 5ba5946daa272fc37552f2ab023f5695e5a15599
